name: Main workflow (PR)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 12]
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: |
          set -x;
          npm i -g yarn
          yarn
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
